force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attendance__c/Course_Attendance__c.object-meta.xml
<CustomObject>
    <label>Course Attendance</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Course Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attendance__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Attendances</relationshipLabel>
    <relationshipName>Course_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/CC_SendDiplomaEmail_Invocable_TST.cls
/**
 * @description       : 
 * @author            : IHU - ihernando@cloudcoachers.com
 * @group             : 
 * @last modified on  : 04-10-2021
 * @last modified by  : IHU - ihernando@cloudcoachers.com
 * Modifications Log 
 * Ver   Date         Author                              Modification
 * 1.0   02-11-2021   IHU - ihernando@cloudcoachers.com   Initial Version
**/
@Istest
private class CC_SendDiplomaEmail_Invocable_TST {

    @TestSetup
    static void makeData(){
        System.debug('CC_SendDiplomaEmail_Invocable_TST.makeData');
        System.debug('CC_SendDiplomaEmail_Invocable_TST.CC_TestDF_CustomSetting.createConfig_Course_Attendance_Notifications');
        CC_TestDF_CustomSetting.createConfig_Course_Attendance_Notifications();
        CC_TestDF_CustomSetting.createConfig_Wordpress_Integration();
        Test.setMock(HttpCalloutMock.class, new CourseTriggerHandlerTest.CourseTriggerHandlerTestMock()); 
        System.debug('CC_SendDiplomaEmail_Invocable_TST.CC_TestDF_Account.createAccountsWithTypeName');
        List<Account> lstAlumnos = CC_TestDF_Account.createAccountsWithTypeName(5, 'PersonAccount');
        System.debug('CC_SendDiplomaEmail_Invocable_TST.CC_TestDF_Course.createRecords');
        List<Course__c> lstCourse = CC_TestDF_Course.createRecords(1);
        System.debug('CC_SendDiplomaEmail_Invocable_TST.CC_TestDF_Course_Attendance.createRecords');
        List<Account> lstAlumnos2 = [SELECT Id,PersonContactId FROM Account WHERE Id IN :lstAlumnos];
        List<Course_Attendance__c> lstAsistentes = CC_TestDF_Course_Attendance.createRecords(lstAlumnos2,lstCourse[0].Id);
    }

    @IsTest
    private static void testSendEmailDiploma(){
        System.debug('CC_SendDiplomaEmail_Invocable_TST.testSendEmailDiploma');
        //GIVEN
        Map<Id, Course_Attendance__c> mapAsistentes = new Map<Id, Course_Attendance__c>([SELECT Id,Name FROM Course_Attendance__c]);
        List<Id> lstIds = new List<Id>(mapAsistentes.keySet());
        //WHEN
        Test.startTest();
        CC_SendDiplomaEmail_Invocable.send(lstIds);
        Test.stopTest();
        //THEN

    }
}