force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_Subject__c.field-meta.xml
<CustomField>
    <fullName>Course_Subject__c</fullName>
    <label>Course Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AWS - Amazon Web Services Fundamentals</fullName>
            </value>
            <value>
                <fullName>Bootcamp Associate</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>Datorama</fullName>
            </value>
            <value>
                <fullName>Einstein Recommendations</fullName>
            </value>
            <value>
                <fullName>Ejercicio Práctico Salesforce</fullName>
            </value>
            <value>
                <fullName>Financial Services Cloud</fullName>
            </value>
            <value>
                <fullName>Google Cloud</fullName>
            </value>
            <value>
                <fullName>Google Professional Cloud Architect</fullName>
            </value>
            <value>
                <fullName>Heroku</fullName>
            </value>
            <value>
                <fullName>Lightning Components</fullName>
                <isActive>false</isActive>
                <label>Lightning Aura Components (Deprecated)</label>
            </value>
            <value>
                <fullName>Lightning Web Component</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud AMPscript</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Developer</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Email</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Email + Admin</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Personalization</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Social</fullName>
            </value>
            <value>
                <fullName>Pardot Consultant</fullName>
            </value>
            <value>
                <fullName>Pardot Specialist</fullName>
            </value>
            <value>
                <fullName>Sales Cloud Implementation</fullName>
            </value>
            <value>
                <fullName>Salesforce ADM and DEV Practice</fullName>
            </value>
            <value>
                <fullName>Salesforce Administration</fullName>
            </value>
            <value>
                <fullName>Salesforce Advanced Administration</fullName>
            </value>
            <value>
                <fullName>B2B Commerce Admin</fullName>
                <label>Salesforce B2B Commerce Admin</label>
            </value>
            <value>
                <fullName>B2B Commerce Dev</fullName>
                <label>Salesforce B2B Commerce Dev</label>
            </value>
            <value>
                <fullName>Salesforce Community Cloud</fullName>
            </value>
            <value>
                <fullName>SF Data Architecture</fullName>
                <label>Salesforce Data Architecture and Management Designer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Ending_Date__c.field-meta.xml
<CustomField>
    <fullName>Ending_Date__c</fullName>
    <label>Ending Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cloud Coachers Madrid</fullName>
            </value>
            <value>
                <fullName>Customer Office</fullName>
            </value>
            <value>
                <fullName>Virtual Training</fullName>
            </value>
            <value>
                <fullName>Other Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9:00h - 12:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 13:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 14:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 15:00h</fullName>
                <default>true</default>
                <label>9:00h - 15:00h</label>
            </value>
            <value>
                <fullName>9:00h - 16:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 17:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 18:00h</fullName>
            </value>
            <value>
                <fullName>10:00h - 14:00h</fullName>
            </value>
            <value>
                <fullName>10:00h - 15:30h</fullName>
            </value>
            <value>
                <fullName>10:00h - 14:30h</fullName>
            </value>
            <value>
                <fullName>13.00h - 16.00h</fullName>
            </value>
            <value>
                <fullName>14:00 - 18:00h</fullName>
            </value>
            <value>
                <fullName>14:00h - 20:00h</fullName>
            </value>
            <value>
                <fullName>14.30h - 18.30h</fullName>
            </value>
            <value>
                <fullName>15:00h - 18.45h</fullName>
            </value>
            <value>
                <fullName>15:00h - 19:00h</fullName>
            </value>
            <value>
                <fullName>15:00h - 20:00h</fullName>
            </value>
            <value>
                <fullName>15:00h - 21:00h</fullName>
            </value>
            <value>
                <fullName>15:30h - 18:30h</fullName>
            </value>
            <value>
                <fullName>15:30h - 19:00h</fullName>
            </value>
            <value>
                <fullName>15:30h - 19:15h</fullName>
            </value>
            <value>
                <fullName>16:00h - 18:00h</fullName>
            </value>
            <value>
                <fullName>16:00h - 19:00h</fullName>
            </value>
            <value>
                <fullName>16:00h - 20:00h</fullName>
            </value>
            <value>
                <fullName>16:30h - 20:30h</fullName>
            </value>
            <value>
                <fullName>17:00h - 19:00h</fullName>
            </value>
            <value>
                <fullName>17:00h - 20:00h</fullName>
            </value>
            <value>
                <fullName>17:00h - 20:30h</fullName>
            </value>
            <value>
                <fullName>17:00h - 21:00h</fullName>
            </value>
            <value>
                <fullName>17:00h - 22:00h</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/SendWebCalendar__c.field-meta.xml
<CustomField>
    <fullName>SendWebCalendar__c</fullName>
    <formula>ISPICKVAL(Course_Type__c, &apos;Calendar Course&apos;) || NOT(ISBLANK(Event_Id_Wordpress__c))</formula>
    <label>Send Web Calendar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not assigned</fullName>
                <default>true</default>
                <label>Not assigned</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Wordpress_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Wordpress_Integration_Status__c</fullName>
    <label>Wordpress Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Resend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Curso de formación</description>
    <label>Course</label>
</RecordType>

force-app/main/default/classes/CourseTriggerHelper.cls
/**
 * @description       : 
 * @author            : IHU - ihernando@cloudcoachers.com
 * @group             : 
 * @last modified on  : 04-05-2021
 * @last modified by  : IHU - ihernando@cloudcoachers.com
 * Modifications Log 
 * Ver   Date         Author                              Modification
 * 1.0   04-05-2021   IHU - ihernando@cloudcoachers.com   Initial Version
**/
public with sharing class CourseTriggerHelper {
    public static void courseCreateEventWPQueable(List<Course__c> newCourseList){
        List<Course__c> courseListWP = new  List<Course__c>();
        for (Course__c course:newCourseList) {
            if (course.SendWebCalendar__c == true) { 
                courseListWP.add(course);
            }
        }
        if (!courseListWP.isEmpty()) {
            CourseWordpressQueue createEventWP = new  courseWordpressQueue(courseListWP) ;
            System.enqueueJob(createEventWP);  
        }
    }
    public static void courseUpdateEventWPQueable(List<Course__c> newCourseList,List<Course__c> oldCourseList){
        List<Course__c> courseListWP = new List<Course__c>();
        for (Integer i=0; i<newCourseList.size(); i++) {
            
            if(newCourseList[i].SendWebCalendar__c == false && oldCourseList[i].SendWebCalendar__c == true){ // Dejar de mostrar
                newCourseList[i].Status__c = 'false';
                courseListWP.add(newCourseList[i]);
            }

            if (newCourseList[i].SendWebCalendar__c == true){ 
                if( newCourseList[i].Start_Date__c      !=  oldCourseList[i].Start_Date__c      || 
                    newCourseList[i].Ending_Date__c     !=  oldCourseList[i].Ending_Date__c     ||
                    newCourseList[i].Course_Subject__c  !=  oldCourseList[i].Course_Subject__c  ||
                    newCourseList[i].Status__c          !=  oldCourseList[i].Status__c      ||
                    newCourseList[i].Schedule__c        !=  oldCourseList[i].Schedule__c    ||
                    newCourseList[i].Location__c        !=  oldCourseList[i].Location__c
                  ){ //Cambia y hay que actualizar o crear
                    courseListWP.add(newCourseList[i]);
                }
                if(newCourseList[i].Wordpress_Integration_Status__c != oldCourseList[i].Wordpress_Integration_Status__c && 
                    newCourseList[i].Wordpress_Integration_Status__c=='Resend'
                  ){  //reenviar por error
                    courseListWP.add(newCourseList[i]);
                }
            }
        }
        if (!courseListWP.isEmpty()) {
            CourseWordpressQueue updateEventWP = new  courseWordpressQueue(courseListWP) ;
            System.enqueueJob(updateEventWP); 
        }   
    }

    public static void courseDeleteEventWPQueable (List<Course__c> oldCourseList){
        List<Course__c> deleteCourseList = new List<Course__c>();
        for (Course__c courseDelete : oldCourseList) {
            Course__c deleteCourseClone = new Course__C();
            deleteCourseClone=courseDelete.clone(false,true,false,false);
            deleteCourseClone.Status__c='false';
            deleteCourseList.add(deleteCourseClone);
        }
        if (!deleteCourseList.isEmpty()) {
            CourseWordpressQueue deleteEventWP = new courseWordpressQueue(deleteCourseList) ;
            System.enqueueJob(deleteEventWP); 
        }
    }
    public static void courseCheckDate (List<Course__c> newCourseList){
        for (Course__c courseCheck : newCourseList) {
            if (courseCheck.Start_Date__c>courseCheck.Ending_Date__c) {
                courseCheck.addError(label.DatesError);
            }
        }
    }
}