force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_Subject__c.field-meta.xml
<CustomField>
    <fullName>Course_Subject__c</fullName>
    <label>Course Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AWS - Amazon Web Services Fundamentals</fullName>
            </value>
            <value>
                <fullName>Bootcamp Associate</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>Datorama</fullName>
            </value>
            <value>
                <fullName>Einstein Recommendations</fullName>
            </value>
            <value>
                <fullName>Ejercicio Práctico Salesforce</fullName>
            </value>
            <value>
                <fullName>Financial Services Cloud</fullName>
            </value>
            <value>
                <fullName>Google Cloud</fullName>
            </value>
            <value>
                <fullName>Google Professional Cloud Architect</fullName>
            </value>
            <value>
                <fullName>Heroku</fullName>
            </value>
            <value>
                <fullName>Lightning Components</fullName>
                <isActive>false</isActive>
                <label>Lightning Aura Components (Deprecated)</label>
            </value>
            <value>
                <fullName>Lightning Web Component</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud AMPscript</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Developer</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Email</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Email + Admin</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Personalization</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud Social</fullName>
            </value>
            <value>
                <fullName>Pardot Consultant</fullName>
            </value>
            <value>
                <fullName>Pardot Specialist</fullName>
            </value>
            <value>
                <fullName>Sales Cloud Implementation</fullName>
            </value>
            <value>
                <fullName>Salesforce ADM and DEV Practice</fullName>
            </value>
            <value>
                <fullName>Salesforce Administration</fullName>
            </value>
            <value>
                <fullName>Salesforce Advanced Administration</fullName>
            </value>
            <value>
                <fullName>B2B Commerce Admin</fullName>
                <label>Salesforce B2B Commerce Admin</label>
            </value>
            <value>
                <fullName>B2B Commerce Dev</fullName>
                <label>Salesforce B2B Commerce Dev</label>
            </value>
            <value>
                <fullName>Salesforce Community Cloud</fullName>
            </value>
            <value>
                <fullName>SF Data Architecture</fullName>
                <label>Salesforce Data Architecture and Management Designer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <label>Course Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Calendar Course</fullName>
            </value>
            <value>
                <fullName>Customer Ad hoc</fullName>
            </value>
            <value>
                <fullName>ISDI Trailhead</fullName>
            </value>
            <value>
                <fullName>ISDI Hands-on</fullName>
            </value>
            <value>
                <fullName>Cert Session</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Ending_Date__c.field-meta.xml
<CustomField>
    <fullName>Ending_Date__c</fullName>
    <label>Ending Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cloud Coachers Madrid</fullName>
            </value>
            <value>
                <fullName>Customer Office</fullName>
            </value>
            <value>
                <fullName>Virtual Training</fullName>
            </value>
            <value>
                <fullName>Other Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>9:00h - 12:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 13:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 14:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 15:00h</fullName>
                <default>true</default>
                <label>9:00h - 15:00h</label>
            </value>
            <value>
                <fullName>9:00h - 16:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 17:00h</fullName>
            </value>
            <value>
                <fullName>9:00h - 18:00h</fullName>
            </value>
            <value>
                <fullName>10:00h - 14:00h</fullName>
            </value>
            <value>
                <fullName>10:00h - 15:30h</fullName>
            </value>
            <value>
                <fullName>10:00h - 14:30h</fullName>
            </value>
            <value>
                <fullName>13.00h - 16.00h</fullName>
            </value>
            <value>
                <fullName>14:00 - 18:00h</fullName>
            </value>
            <value>
                <fullName>14:00h - 20:00h</fullName>
            </value>
            <value>
                <fullName>14.30h - 18.30h</fullName>
            </value>
            <value>
                <fullName>15:00h - 18.45h</fullName>
            </value>
            <value>
                <fullName>15:00h - 19:00h</fullName>
            </value>
            <value>
                <fullName>15:00h - 20:00h</fullName>
            </value>
            <value>
                <fullName>15:00h - 21:00h</fullName>
            </value>
            <value>
                <fullName>15:30h - 18:30h</fullName>
            </value>
            <value>
                <fullName>15:30h - 19:00h</fullName>
            </value>
            <value>
                <fullName>15:30h - 19:15h</fullName>
            </value>
            <value>
                <fullName>16:00h - 18:00h</fullName>
            </value>
            <value>
                <fullName>16:00h - 19:00h</fullName>
            </value>
            <value>
                <fullName>16:00h - 20:00h</fullName>
            </value>
            <value>
                <fullName>16:30h - 20:30h</fullName>
            </value>
            <value>
                <fullName>17:00h - 19:00h</fullName>
            </value>
            <value>
                <fullName>17:00h - 20:00h</fullName>
            </value>
            <value>
                <fullName>17:00h - 20:30h</fullName>
            </value>
            <value>
                <fullName>17:00h - 21:00h</fullName>
            </value>
            <value>
                <fullName>17:00h - 22:00h</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not assigned</fullName>
                <default>true</default>
                <label>Not assigned</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Curso de formación</description>
    <label>Course</label>
</RecordType>

force-app/main/default/classes/CourseTriggerHandlerTest.cls
/**
 * @File Name          : CourseTriggerHandlerTest.cls
 * @Description        : 
 * @Author             : Juanan jrubio@cloudcoachers.com
 * @Group              : 
 * @Last Modified By   : IHU - ihernando@cloudcoachers.com
 * @Last Modified On   : 04-11-2021
 * @Modification Log   : 
 * Ver       Date            Author      		            Modification
 * 1.0    11/03/2020   Juanan jrubio@cloudcoachers.com     Initial Version
**/
@isTest
public with sharing class CourseTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        CC_TestDF_CustomSetting.createConfig_Wordpress_Integration();
        Test.setMock(HttpCalloutMock.class, new CourseTriggerHandlerTestMock('1111')); 
        List<Course__c> testList= new List<Course__c>();
            Course__c testCourse = new Course__c();
            testCourse.RecordTypeId='0121p000000oVSiAAM';
            testCourse.Course_Type__c='ISDI Trailhead';
            testCourse.Name='testName';
            testCourse.Course_Subject__c='Pardot Consultant';
            testCourse.Ending_Date__c=Date.today().addDays(5);
            testCourse.Location__c='Cloud Coachers Madrid';
            testCourse.Schedule__c='9:00h - 12:00h';
            testCourse.Start_Date__c=Date.today();
            testCourse.Status__c='Open';
            testList.add(testCourse);
        insert testList;
    }
    @isTest static void testCreateEvent() {
        List<Course__c> testList= new List<Course__c>();
            Course__c testCourse = new Course__c();
            testCourse.RecordTypeId='0121p000000oVSiAAM';
            testCourse.Course_Type__c='Calendar Course';
            testCourse.Name='testName';
            testCourse.Course_Subject__c='Pardot Consultant';
            testCourse.Ending_Date__c=Date.today().addDays(5);
            testCourse.Location__c='Cloud Coachers Madrid';
            testCourse.Schedule__c='9:00h - 12:00h';
            testCourse.Start_Date__c=Date.today();
            testCourse.Status__c='Open';
            testList.add(testCourse);
        insert testList;
        CourseTriggerHandlerTestMock mockClass= new CourseTriggerHandlerTestMock();
        mockClass.saleforceId=testList[0].id;
        mockClass.status=true;
        Test.setMock(HttpCalloutMock.class, mockClass);
    }    
    @isTest static void testUpdateEvent() {
        List<Course__c> testListNew= [SELECT id,Ending_Date__c,Course_Type__c FROM Course__c];
        for (Course__c updatecourse : testListNew) {
            updatecourse.Ending_Date__c=Date.today().addDays(10);
            updatecourse.Course_Type__c='Calendar Course';
        }
        update testListNew;
        CourseTriggerHandlerTestMock mockClass= new CourseTriggerHandlerTestMock();
        mockClass.saleforceId=testListNew[0].id;
        mockClass.status=true;
        Test.setMock(HttpCalloutMock.class, mockClass);
    } 
    @isTest static void testUpdateEventErrorDates() {
        List<Course__c> testListNew= [SELECT id,Ending_Date__c,Course_Type__c FROM Course__c];
        for (Course__c updatecourse : testListNew) {
            updatecourse.Ending_Date__c=Date.newInstance(1995, 04, 25);
            updatecourse.Course_Type__c='Calendar Course';
        }
        try {
            update testListNew;
        } catch (Exception e) {
            Boolean Error =  e.getMessage().contains(label.DatesError) ? true : false;
            System.AssertEquals(true, Error);
        }
    } 
    @isTest static void testUpdateEventErrorJson() {
        List<Course__c> testListNew= [SELECT id,Ending_Date__c,Course_Type__c FROM Course__c];
        for (Course__c updatecourse : testListNew) {
            updatecourse.Course_Type__c='Calendar Course';
            updatecourse.Ending_Date__c=Date.today().addDays(10);
        }        
        update testListNew;
        CourseTriggerHandlerTestMockErrorJson mockClass= new CourseTriggerHandlerTestMockErrorJson();
        mockClass.saleforceId=testListNew[0].id;
        mockClass.status=true;
        Test.setMock(HttpCalloutMock.class, mockClass);
    } 
    @isTest static void testUpdateEventErrorConection() {
        List<Course__c> testListNew= [SELECT id,Ending_Date__c,Course_Type__c FROM Course__c];
        for (Course__c updatecourse : testListNew) {
            updatecourse.Course_Type__c='Calendar Course';
            updatecourse.Ending_Date__c=Date.today().addDays(10);
        }        
        update testListNew;
        CourseTriggerHandlerTestMockErrorConection mockClass= new CourseTriggerHandlerTestMockErrorConection();
        mockClass.saleforceId=testListNew[0].id;
        mockClass.status=true;
        Test.setMock(HttpCalloutMock.class, mockClass);
    } 
    @isTest static void testDeleteEvent() {
        List<Course__c> testListNew= [SELECT id FROM Course__c];
        // Set mock callout class 
        CourseTriggerHandlerTestMock mockClass= new CourseTriggerHandlerTestMock();
        mockClass.saleforceId=testListNew[0].id;
        mockClass.status=false;
        Test.setMock(HttpCalloutMock.class, mockClass);
        test.startTest();
        delete testListNew;
        test.stopTest();
    } 
    public class CourseTriggerHandlerTestMock implements HttpCalloutMock{
        public String saleforceId; 
        public Boolean status;
        public String EventIdWordpress;

        public CourseTriggerHandlerTestMock(){
            this.EventIdWordpress = '483';
        }

        public CourseTriggerHandlerTestMock(String EventIdWordpress){
            this.EventIdWordpress = EventIdWordpress;
        }
        
        public HttpResponse respond(HTTPRequest req){
            HttpResponse res = new HttpResponse();
            res.setStatus('OK');
            res.setStatusCode(200);
            res.setBody('[{"Wordpress_Integration_Error_Message":"OK","Event_Id_Wordpress":' + EventIdWordpress + ',"IdSF":"'+saleforceId+'","Wordpress_Integration_Status":"Confirmed","Wordpress_Last_Synchronization":"2020-11-03 16:47:05","Status":'+status+'}]');
            return res;
        }
    }
    public class CourseTriggerHandlerTestMockErrorJson implements HttpCalloutMock{
        public String saleforceId; 
        public Boolean status;
        public HttpResponse respond(HTTPRequest req){
            HttpResponse res = new HttpResponse();
            res.setStatus('OK');
            res.setStatusCode(200);
            res.setBody('error en el json');
            return res;
        }
    }
    public class CourseTriggerHandlerTestMockErrorConection implements HttpCalloutMock{
        public String saleforceId; 
        public Boolean status;
        public HttpResponse respond(HTTPRequest req){
            HttpResponse res = new HttpResponse();
            res.setStatus('Error');
            res.setStatusCode(401);
            res.setBody('fail connexion');
            return res;
        }
    }
}