force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <description>Curso de formación</description>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Course_Attendance__c/Course_Attendance__c.object-meta.xml
<CustomObject>
    <label>Course Attendance</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Course Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attendance__c/fields/Attendant__c.field-meta.xml
<CustomField>
    <fullName>Attendant__c</fullName>
    <label>Attendant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Attendances</relationshipLabel>
    <relationshipName>Course_Attendances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Attendance__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Attendances</relationshipLabel>
    <relationshipName>Course_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CC_TestDF_Course_Attendance.cls
/**
* @author Cloud Coachers S.L.
* @date 17/02/2021
* @description Clase de test para la generacion del Object Course.
* @group Test
<pre>
FECHA                 AUTOR                    ACCION
17/02/2021            IHU                      Creación.

</pre>
*/
@isTest
public class CC_TestDF_Course_Attendance {

	public static List<Course_Attendance__c> createRecords(List<Account> lstAlumnos, Id courseId ){
		List<Course_Attendance__c> returnedRecords = createVariableRecords(lstAlumnos, courseId);
		insert returnedRecords;
		return returnedRecords;
	}

	public static List<Course_Attendance__c> createVariableRecords(List<Account> lstAlumnos, Id courseId){
		List<Course_Attendance__c> returnedRecords = new List<Course_Attendance__c>();
		for(Account acc : lstAlumnos){
			Course_Attendance__c auxRecord = new Course_Attendance__c();
			System.debug('acc: ' + acc + ' - ' + acc.PersonContactId);
			fillSystemRequireFields(auxRecord, acc.PersonContactId, courseId);
			returnedRecords.add(auxRecord);
		}
		return returnedRecords;
	}

	private static void fillSystemRequireFields(Course_Attendance__c record, Id contactId, Id courseId){
        record.Attendant__c = contactId;
        record.Course__c = courseId;
	}	
	
}