force-app/main/default/objects/CC_CifAndWeb__c/CC_CifAndWeb__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CIF &amp; Web CC</label>
</CustomObject>

force-app/main/default/objects/CC_CifAndWeb__c/fields/CC_CIF__c.field-meta.xml
<CustomField>
    <fullName>CC_CIF__c</fullName>
    <label>CIF</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_CifAndWeb__c/fields/CC_Web__c.field-meta.xml
<CustomField>
    <fullName>CC_Web__c</fullName>
    <label>CC Web</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Proforma</fullName>
            </value>
            <value>
                <fullName>Presupuesto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RH</fullName>
            </value>
            <value>
                <fullName>TSS</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COA</fullName>
            </value>
            <value>
                <fullName>GCP</fullName>
            </value>
            <value>
                <fullName>SLL</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>FC</fullName>
                <label>FCO</label>
            </value>
            <value>
                <fullName>NOM</fullName>
            </value>
            <value>
                <fullName>CNTSS</fullName>
            </value>
            <value>
                <fullName>CNCOA</fullName>
            </value>
            <value>
                <fullName>TFR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/InvoiceLine__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>INV-LINE-{0000000000}</displayFormat>
        <label>Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLine__c/fields/AmountDiscount__c.field-meta.xml
<CustomField>
    <fullName>AmountDiscount__c</fullName>
    <label>Amount Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0%</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4%</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10%</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>21%</label>
            </value>
            <value>
                <fullName>4.5</fullName>
                <label>4.5%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CC_InvoiceDocument_TST.cls
/**
 * @File Name          : CC_InvoiceDocument_TST .cls
 * @Description        : 
 * @Author             : TXU - jmurdiain@cloudcoachers.com
 * @Group              : 
 * @Last Modified By   : TXU - jmurdiain@cloudcoachers.com
 * @Last Modified On   : 3/16/2020, 11:42:36 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    2/25/2020   TXU - jmurdiain@cloudcoachers.com     Initial Version
**/
@isTest
public with sharing class CC_InvoiceDocument_TST {
    @isTest static void test_Controller() {
        List<Account> accLst = CC_TestDF_Account.createAccounts(1);
        Invoice__c invoice = new Invoice__c();
        invoice.AccountId__c = accLst[0].Id;
        invoice.Type__c = 'TSS';
        invoice.Status__c = 'Draft';
        invoice.InvoiceDate__c = date.newinstance(1960, 2, 17);
        insert invoice;

        InvoiceLine__c invLine = new InvoiceLine__c();
        invLine.AmountDiscount__c = 100;
        invLine.Description__c = 'Hola';
        invLine.Discount__c = 0.1;
        invLine.InvoiceId__c = invoice.Id;
        invLine.AmountDiscount__c = 100;
        //invLine.ProductId__c
        invLine.Quantity__c = 2;
        invLine.Tax__c = '21';
        invLine.UnitPrice__c = 2000;
        insert invLine;

        CC_CifAndWeb__c cifAndWeb = new CC_CifAndWeb__c();
        cifAndWeb.CC_CIF__c = 'B83644853';
        cifAndWeb.CC_Web__c = 'www.cloudcoachers.com';
        cifAndWeb.SetupOwnerId = UserInfo.getOrganizationId();
        insert cifAndWeb;
    
        CC_InvoiceDocument_CTR controller = new CC_InvoiceDocument_CTR();
        controller.setIdInvoice(invoice.Id);

        controller.getIdInvoice();
    }
}