force-app/main/default/objects/Account/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <label>Razón Social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>CC Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccount__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>34</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAccount__c/fields/Swift__c.field-meta.xml
<CustomField>
    <fullName>Swift__c</fullName>
    <label>Swift</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_CifAndWeb__c/CC_CifAndWeb__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CIF &amp; Web CC</label>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BankAccountId__c.field-meta.xml
<CustomField>
    <fullName>BankAccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CC Bank Account</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>Billing Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>BillingPostalCode__c</fullName>
    <label>Billing Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <label>Discount Amount</label>
    <summarizedField>InvoiceLine__c.DiscountAmount__c</summarizedField>
    <summaryForeignKey>InvoiceLine__c.InvoiceId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <formula>InvoiceDate__c + Value(Text( PaymentTerms__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>NetAmountWithoutWithholding__c - (NetAmountWithoutWithholding__c* Withholding__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/NetAmountWithoutWithholding__c.field-meta.xml
<CustomField>
    <fullName>NetAmountWithoutWithholding__c</fullName>
    <label>Net Amount Without Withholding</label>
    <summarizedField>InvoiceLine__c.NetAmount__c</summarizedField>
    <summaryForeignKey>InvoiceLine__c.InvoiceId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Proforma</fullName>
            </value>
            <value>
                <fullName>Presupuesto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TaxAmount__c.field-meta.xml
<CustomField>
    <fullName>TaxAmount__c</fullName>
    <label>Tax Amount</label>
    <summarizedField>InvoiceLine__c.TaxAmount__c</summarizedField>
    <summaryForeignKey>InvoiceLine__c.InvoiceId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>InvoiceLine__c.TotalPrice__c</summarizedField>
    <summaryForeignKey>InvoiceLine__c.InvoiceId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Withholding__c.field-meta.xml
<CustomField>
    <fullName>Withholding__c</fullName>
    <label>Withholding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/WithholdingAmount__c.field-meta.xml
<CustomField>
    <fullName>WithholdingAmount__c</fullName>
    <formula>NetAmountWithoutWithholding__c * Withholding__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Withholding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/InvoiceLine__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>INV-LINE-{0000000000}</displayFormat>
        <label>Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLine__c/fields/Description_Rich__c.field-meta.xml
<CustomField>
    <fullName>Description_Rich__c</fullName>
    <label>Description (Rich)</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <formula>IF(ISPICKVAL( DiscountType__c , &quot;Percentage&quot;), Discount__c * TotalPrice__c, AmountDiscount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/DiscountType__c.field-meta.xml
<CustomField>
    <fullName>DiscountType__c</fullName>
    <label>DiscountType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>IF(ISPICKVAL( DiscountType__c , &quot;Percentage&quot;), (1 - Discount__c) * TotalPrice__c, TotalPrice__c -  AmountDiscount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0%</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4%</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10%</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>21%</label>
            </value>
            <value>
                <fullName>4.5</fullName>
                <label>4.5%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/TaxAmount__c.field-meta.xml
<CustomField>
    <fullName>TaxAmount__c</fullName>
    <formula>NetAmount__c * (Value(Text(Tax__c))/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>NetAmount__c + TaxAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <formula>Quantity__c * UnitPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CC_InvoiceDocument_CTR.cls
/**
 * @File Name          : CC_InvoiceDocument_CTR.cls
 * @Description        : 
 * @Author             : IHU - ihernando@cloudcoachers.com
 * @Group              : 
 * @Last Modified By   : IHU - ihernando@cloudcoachers.com
 * @Last Modified On   : 07-03-2020
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    2/27/2020   TXU - jmurdiain@cloudcoachers.com     Initial Version
**/
public with sharing class CC_InvoiceDocument_CTR {
    public Id idInvoice;
    public Invoice__c invoice{get;set;}
    public Organization cloudCoachers{get; private set;}
    public CC_CifAndWeb__c ccData {get;private set;}
    public Boolean showDiscount {get; private set;}
    public List<InvoiceLine__c> ivaLst{get; private set;}
    public List<TotalTaxes> lstTaxes{get; private set;}
    

    public void setIdInvoice(Id idsf){
        Map<String,TotalTaxes> mapTaxes = new Map<String,TotalTaxes>();
        this.idInvoice = idsf;
        this.invoice = [SELECT Withholding__c,(SELECT id, UnitPrice__c, TaxAmount__c, DiscountType__c,DiscountAmount__c, Name,ProductId__r.Name, Quantity__c,Discount__c,Tax__c,NetAmount__c, TotalAmount__c,TotalPrice__c, Description__c, Description_Rich__c FROM Invoice_Lines__r), BankAccountId__r.Bank_Name__c, BankAccountId__r.IBAN__c, BankAccountId__r.Owner__c, BankAccountId__r.Swift__c, id,Total_Price__c,Name,Notes__c, Invoice_Number__c,InvoiceDate__c,DiscountAmount__c,NetAmount__c, TaxAmount__c,TotalAmount__c , AccountId__c,Status__c,DueDate__c, VATNumber__c, BillingStreet__c, BillingState__c, BillingPostalCode__c, BillingCountry__c, AccountId__r.Business_Name__c, NetAmountWithoutWithholding__c, WithholdingAmount__c FROM Invoice__c WHERE id = :idInvoice];
        
        cloudCoachers =[SELECT id, Name, Street, state, PostalCode, Country FROM Organization];
        
        ccData = CC_CifAndWeb__c.getInstance();

        if(this.invoice.DiscountAmount__c > 0){
            this.showDiscount = true;
        }else{
            this.showDiscount = false;
        }
        for (InvoiceLine__c invo : this.invoice.Invoice_Lines__r) {
            if(invo.Tax__c != '0' && invo.Tax__c != null){
                if (mapTaxes.containsKey(invo.Tax__c)){
                    mapTaxes.put(invo.Tax__c, new TotalTaxes(mapTaxes.get(invo.Tax__c).tax,mapTaxes.get(invo.Tax__c).amount+invo.TaxAmount__c));
                }else{
                    TotalTaxes totTaxes = new TotalTaxes(invo.Tax__c,invo.TaxAmount__c);
                    mapTaxes.put(invo.Tax__c,totTaxes);
                }
            }
        }

        this.lstTaxes = mapTaxes.values();
        System.debug(lstTaxes);
    }
    public Id getIdInvoice(){
        return this.idInvoice;
    }

    private class TotalTaxes {
        public String tax;
        public Decimal amount = 0 ;
        public TotalTaxes (String tax, Decimal amount){
            this.tax = tax;
            this.amount = amount;
        }
        public String getTax(){
            return this.tax;
        }
        public Decimal getAmount(){
            return this.amount;
        }
    }
}