force-app/main/default/objects/Config_Course_Attendance_Notifications__c/Config_Course_Attendance_Notifications__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Course Attendance Notifications</label>
</CustomObject>

force-app/main/default/objects/Config_Course_Attendance_Notifications__c/fields/Diploma_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Diploma_File_Name__c</fullName>
    <label>Diploma_File_Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Config_Course_Attendance_Notifications__c/fields/OrgWideEmailAddress_Id__c.field-meta.xml
<CustomField>
    <fullName>OrgWideEmailAddress_Id__c</fullName>
    <label>OrgWideEmailAddress_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WPConfig__c/WPConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>WP Config</label>
</CustomObject>

force-app/main/default/classes/CC_TestDF_CustomSetting.cls
/**
 * @description       : 
 * @author            : IHU - ihernando@cloudcoachers.com
 * @group             : 
 * @last modified on  : 04-10-2021
 * @last modified by  : IHU - ihernando@cloudcoachers.com
 * Modifications Log 
 * Ver   Date         Author                              Modification
 * 1.0   02-17-2021   IHU - ihernando@cloudcoachers.com   Initial Version
**/
@Istest
public class CC_TestDF_CustomSetting {

    public static void createConfig_Course_Attendance_Notifications() {
        Config_Course_Attendance_Notifications__c configCourseAttendanceNotification;
        configCourseAttendanceNotification = new Config_Course_Attendance_Notifications__c();
        configCourseAttendanceNotification.Diploma_File_Name__c ='Diploma';
        /*List<OrgWideEmailAddress> lstOrgWideEmailAddress = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        if(lstOrgWideEmailAddress.size()>0){
            configCourseAttendanceNotification.OrgWideEmailAddress_Id__c = lstOrgWideEmailAddress[0].Id;
        }*/
        configCourseAttendanceNotification.SetupOwnerId = UserInfo.getOrganizationId();
        insert configCourseAttendanceNotification; 
    }
    
    public static void createConfig_Wordpress_Integration() {
        WPConfig__c wPConfig = WPConfig__c.getInstance();
        wPConfig.Secret__c = 'Secreto';
        wPConfig.endPoint__c = 'https://www.cloudcoachers.com/wp-json/salesforce/events/'; 
        insert wPConfig; 
    }
}